%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(gwc_proto).
-define(gwc_proto, true).

-define(gwc_proto_gpb_version, "3.26.4").

-ifndef('BROADCAST_PB_H').
-define('BROADCAST_PB_H', true).
-record('Broadcast',
        {serverType             :: binary() | iolist() | undefined, % = 1
         serverID               :: binary() | iolist() | undefined, % = 2
         payload                :: binary() | undefined % = 3
        }).
-endif.

-ifndef('UIDS_PB_H').
-define('UIDS_PB_H', true).
-record('Uids',
        {uid                    :: binary() | iolist() | undefined % = 1
        }).
-endif.

-ifndef('REPORTSERVERINFO_PB_H').
-define('REPORTSERVERINFO_PB_H', true).
-record('ReportServerInfo',
        {serverType             :: binary() | iolist() | undefined, % = 1
         serverID               :: binary() | iolist() | undefined, % = 2
         serverURI              :: binary() | iolist() | undefined, % = 3
         gwcURI                 :: binary() | iolist() | undefined, % = 4
         max                    :: integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('NOTIFYCLOSE_PB_H').
-define('NOTIFYCLOSE_PB_H', true).
-record('NotifyClose',
        {uid                    :: binary() | iolist() | undefined % = 1
        }).
-endif.

-ifndef('HEARTBEATRES_PB_H').
-define('HEARTBEATRES_PB_H', true).
-record('HeartbeatRes',
        {
        }).
-endif.

-ifndef('TICKUSER_PB_H').
-define('TICKUSER_PB_H', true).
-record('TickUser',
        {uid                    :: binary() | iolist() | undefined % = 1
        }).
-endif.

-ifndef('HEARTBEATREQ_PB_H').
-define('HEARTBEATREQ_PB_H', true).
-record('HeartbeatReq',
        {
        }).
-endif.

-ifndef('BROADCASTBYUID_PB_H').
-define('BROADCASTBYUID_PB_H', true).
-record('BroadcastByUID',
        {uids = []              :: [#'Uids'{}],     % = 1
         payload                :: binary() | undefined % = 2
        }).
-endif.

-endif.
