%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(inner_msg_proto).
-define(inner_msg_proto, true).

-define(inner_msg_proto_gpb_version, "3.26.4").

-ifndef('INNERREGISTPROXY_PB_H').
-define('INNERREGISTPROXY_PB_H', true).
-record('InnerRegistProxy',
        {id                     :: integer(),       % = 1, 32 bits
         ip                     :: binary() | iolist(), % = 2
         port                   :: integer()        % = 3, 32 bits
        }).
-endif.

-endif.
