%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.4

-ifndef(hall_proto).
-define(hall_proto, true).

-define(hall_proto_gpb_version, "3.26.4").

-ifndef('GAME_PB_H').
-define('GAME_PB_H', true).
-record('Game',
        {id                     :: integer() | undefined, % = 1, 32 bits
         name                   :: binary() | iolist() | undefined, % = 2
         intro                  :: binary() | iolist() | undefined, % = 3
         config                 :: binary() | iolist() | undefined, % = 4
         game_screen            :: integer() | undefined, % = 5, 32 bits
         introduce              :: binary() | iolist() | undefined, % = 6
         pic_small              :: binary() | iolist() | undefined, % = 7
         pic_big                :: binary() | iolist() | undefined, % = 8
         flag                   :: integer() | undefined % = 9, 32 bits
        }).
-endif.

-ifndef('CHANGEUSERICONRES_PB_H').
-define('CHANGEUSERICONRES_PB_H', true).
-record('ChangeUserIconRes',
        {code                   :: integer() | undefined, % = 1, 32 bits
         uid                    :: binary() | iolist() | undefined % = 2
        }).
-endif.

-ifndef('COMMONSTATUS_PB_H').
-define('COMMONSTATUS_PB_H', true).
-record('CommonStatus',
        {code                   :: integer() | undefined, % = 1, 32 bits
         msg                    :: binary() | iolist() | undefined % = 2
        }).
-endif.

-ifndef('GAMELISTRES_PB_H').
-define('GAMELISTRES_PB_H', true).
-record('GameListRes',
        {gameList = []          :: [#'Game'{}]      % = 1
        }).
-endif.

-ifndef('CHANGEUSERICONREQ_PB_H').
-define('CHANGEUSERICONREQ_PB_H', true).
-record('ChangeUserIconReq',
        {head_id                :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('GAMELISTREQ_PB_H').
-define('GAMELISTREQ_PB_H', true).
-record('GameListReq',
        {channel_id             :: binary() | iolist() | undefined % = 1
        }).
-endif.

-ifndef('MSG_PB_H').
-define('MSG_PB_H', true).
-record('Msg',
        {action                 :: non_neg_integer() | undefined, % = 1, 32 bits
         msgBody                :: binary() | undefined % = 2
        }).
-endif.

-ifndef('VERIFYRES_PB_H').
-define('VERIFYRES_PB_H', true).
-record('VerifyRes',
        {id                     :: binary() | iolist() | undefined, % = 1
         username               :: binary() | iolist() | undefined, % = 2
         nickname               :: binary() | iolist() | undefined, % = 3
         channel_id             :: binary() | iolist() | undefined, % = 4
         platform               :: binary() | iolist() | undefined, % = 5
         icon                   :: binary() | iolist() | undefined, % = 6
         gold                   :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 7
         valid_gold             :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 8
         create_time            :: binary() | iolist() | undefined, % = 9
         invite_code            :: binary() | iolist() | undefined % = 10
        }).
-endif.

-ifndef('VERIFYREQ_PB_H').
-define('VERIFYREQ_PB_H', true).
-record('VerifyReq',
        {identity               :: binary() | iolist() | undefined, % = 1
         channel_id             :: binary() | iolist() | undefined % = 2
        }).
-endif.

-endif.
