%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(call_service_thrift).
-behaviour(thrift_service).


-include("call_service_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info(_) -> erlang:error(function_clause).
%%% interface
% call(This, M)
function_info('call', params_type) ->
  {struct, [{1, {struct, {'call_types', 'Message'}}}]}
;
function_info('call', reply_type) ->
  {struct, {'call_types', 'Message'}};
function_info('call', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> erlang:error(function_clause).

